Add cloudmesh-docker repo to docker bundle
cloudmesh/cloudmesh-installer pull request #2
Opened 2020-10-18 21:54 UTC by reillymarkowitz

Currently, the only way to install `cloudmesh-docker` using `cloudmesh-installer` is by downloading the "source" bundle, which includes over 30 additional packages:

![Screen Shot 2020-10-18 at 5 46 21 PM](https://user-images.githubusercontent.com/13988685/96386579-f97eb100-1169-11eb-8099-9c6610778f78.png)

There's also a "docker" bundle that doesn't contain `cloudmesh-docker`:

![Screen Shot 2020-10-18 at 5 51 20 PM](https://user-images.githubusercontent.com/13988685/96386657-8a558c80-116a-11eb-971f-7a5804663b4c.png)

This PR adds `cloudmesh-docker` to the "docker" bundle so that users can install `cloudmesh-docker` without installing 30+ additional packages.

2020-10-18 22:05 UTC, laszewsk requested changes
This has to be done differently.

docker here means cmsd which is a dockerized container of cms

whet we do here is a different thing we start a docker command that uses docker from within cms not as the other package the uses docker from the outside.

We realize this can lead to confusion, but we had so far no docker command. so we need to start thinking about propper bundle names. As we use docker before it is unwise to make that change as it could impact the documentation of cmsd and lead to big confusions. 

I have not yet thought about a proper bundle name for the docker command.

maybe "docker-command" would be ok

2020-10-18 22:06 UTC, laszewsk commented
This is a good find, but not as easy to fix ...

2020-10-18 22:14 UTC, laszewsk commented
I have added a bundle "docker-command" but did not yet provide any documentation for it. I think it deserves special attention and adds to the documentation in cloudmesh-docker and cloudmesh-cmsd

I think we need to add this even to the man pages.

2020-10-18 23:10 UTC, reillymarkowitz commented
Closing this PR because 2d2933ee98a2f7960464b71b869ef1726cd7f2fa introduces a new "docker-command" bundle that solves the issue

2020-10-18 23:10 UTC, closed without merging

2020-10-18 23:30 UTC, laszewsk commented
reopen the pull request as we need to make sure the documentation gets fixed and addresses teh existence of 

docker 
vs
docker-command

2020-10-20 23:42 UTC, reillymarkowitz commented
Updated documentation for `cloudmesh-docker`: https://github.com/cloudmesh/cloudmesh-docker/pull/4 (merged)

It contained the only mention of `cloudmesh-installer get docker` or `cloudmesh-installer get docker-command`  in all the repos across the org.